GET http://localhost:5056/todos

###
GET http://localhost:5056/todos/1

###
POST http://localhost:5056/todos
Content-Type: application/json

{
    "Title": "Do Homework",
    "DueDate": "2029-04-23T16:30"
}

### 
DELETE http://localhost:5056/todos/2

###
PATCH http://localhost:5056/todos/1
Content-Type: application/json

{
    "IsCompleted": true
}

###
GET http://localhost:5056/todos/completed

###
GET http://localhost:5056/todos/pending

###
GET http://localhost:5056/todos/find?title=sh
